KFold() argument: explicitly assigned because tyep error below occured when ran on HTC:
TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given